### ISSUE TITLE
Issues with using H3 package on Lambda

### ISSUE THREAD

**Issue by criscode97** [uber/h3-py#303]
I am trying to create a lambda layer using h3. all attempts have ended with: "errorMessage": "Unable to import module 'lambda_function': No module named 'h3._cy.cells'"
I am doing this using docker inside an ubuntu image on my mac with arm64. I have tried installing it with the following .whl files with no avail:

h3-3.7.6-cp310-cp310-win_amd64.whl
h3-3.7.6-cp310-cp310-musllinux_1_1_x86_64.whl
h3-3.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
h3-3.7.6-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

I have also attempted to install it by simply using pip3 install h3

Any Help is appreciated!

**Comment by kylebarron** [comment]
Usually pip will correctly find the right wheel and you shouldn't need to do anything manual. You should try updating pip to the latest version. Otherwise you need to give more information about your setup and python version, linux arch, etc.

**Comment by dubey44** [comment]
@kylebarron facing issue with lambda, not in local machine.

**Comment by kylebarron** [comment]
You should install it from a Lambda docker container to build your distribution, then you'll get the relevant pip package.

**Comment by aum7** [comment]
olo

i also have same issue

os: mint 21.3

trying to use timezonefinder with blender3d app
importing timezonefinder into blender gives h3 error : 

`import timezonefinder
Traceback (most recent call last):
File "<blender_console>", line 1, in
File "/home/aumhren/.local/lib/python3.10/site-packages/timezonefinder/init.py", line 1, in
from timezonefinder.timezonefinder import TimezoneFinder, TimezoneFinderL
File "/home/aumhren/.local/lib/python3.10/site-packages/timezonefinder/timezonefinder.py", line 9, in
from h3.api import numpy_int as h3
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/init.py", line 3, in
from .api.basic_str import *
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/api/init.py", line 3, in
from . import basic_int
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/api/basic_int/init.py", line 1, in
from ._public_api import * # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/api/basic_int/_public_api.py", line 9, in
from ._binding import _binding
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/api/basic_int/_binding.py", line 16, in
from ... import _cy
File "/home/aumhren/.local/lib/python3.10/site-packages/h3/_cy/init.py", line 16, in
from .cells import (
ModuleNotFoundError: No module named 'h3._cy.cells'`

i tried updating pip, no luck

thx for sharing

have fun

**Comment by charlieforward9** [comment]
I am experiencing this issue as well. 

Python version: 3.12
Linux Arch: x86
Linux Image: amazonlinux2023

All i need is the `latlng_to_cell` method. 

I am available to provide any other information necessary, this is a major blocking issue for me.

**Comment by nojimatakashi55** [comment]
Just to clarify — I was able to get `h3-py` working in AWS Lambda with Python 3.12 on Amazon Linux 2023 by installing it into a custom Lambda Layer using the following `pip` command:

```bash
python -m pip install h3==4.2.2 \
     --python-version 3.12 \
     --target=python \
     --platform manylinux2014_x86_64 \
     --implementation cp \
     --no-deps \
     --only-binary=:all: \
     --no-cache-dir \
     --upgrade
```

Then I zipped the python/ folder and uploaded it as a Lambda Layer.
This worked without issues in my environment.

Hope this helps someone facing similar deployment problems!

**Comment by charlieforward9** [comment]
This worked for me! Thank you. Looks like this can be closed with this solution.
