### ISSUE TITLE
windows 10 64bit cmake error

### ISSUE THREAD

**Issue by zapcity** [uber/h3-py#49]
I am trying to install h3 on Windows 10 64bit. I have installed python 3.7.4 (via python.org) and all the other requirements i.e. Git for Windows, CMake, and Visual Studio 2019 with C/C++ component. However when trying to install via 'pip install h3' I get the following:

```
C:\Python37>pip install h3
Collecting h3
  Using cached https://files.pythonhosted.org/packages/98/2a/704b2db80465ce3a412d6c94f1c1658cffbbb4e76c5c03bb133f588cc131/h3-3.4.3.tar.gz
Building wheels for collected packages: h3
  Building wheel for h3 (setup.py) ... error
  ERROR: Complete output from command 'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jwalker\\AppData\\Local\\Temp\\pip-install-xav63t6b\\h3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jwalker\AppData\Local\Temp\pip-wheel-0rikge7d' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\h3
  copying h3\h3.py -> build\lib.win-amd64-3.7\h3
  copying h3\__init__.py -> build\lib.win-amd64-3.7\h3
  running build_ext
  + VERSION=v3.4.2
  + IS_64BITS=True
  + '[' '' == v3.4.2 ']'
  + command -v cmake
  + echo 'cmake required but not found.'
  cmake required but not found.
  + exit 1
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 65, in <module>
      distclass=BinaryDistribution)
    File "c:\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python37\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 25, in run
      install_h3(h3_version)
    File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 18, in install_h3
      subprocess.check_call('bash ./.install.sh {} {}'.format(h3_version, is_64bits), shell=True)
    File "c:\python37\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'bash ./.install.sh v3.4.2 True' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for h3
  Running setup.py clean for h3
Failed to build h3
Installing collected packages: h3
  Running setup.py install for h3 ... error
    ERROR: Complete output from command 'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jwalker\\AppData\\Local\\Temp\\pip-install-xav63t6b\\h3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jwalker\AppData\Local\Temp\pip-record-25qy8tes\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\h3
    copying h3\h3.py -> build\lib.win-amd64-3.7\h3
    copying h3\__init__.py -> build\lib.win-amd64-3.7\h3
    running build_ext
    + VERSION=v3.4.2
    + IS_64BITS=True
    + '[' '' == v3.4.2 ']'
    + command -v cmake
    + echo 'cmake required but not found.'
    cmake required but not found.
    + exit 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 65, in <module>
        distclass=BinaryDistribution)
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 25, in run
        install_h3(h3_version)
      File "C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\setup.py", line 18, in install_h3
        subprocess.check_call('bash ./.install.sh {} {}'.format(h3_version, is_64bits), shell=True)
      File "c:\python37\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'bash ./.install.sh v3.4.2 True' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jwalker\\AppData\\Local\\Temp\\pip-install-xav63t6b\\h3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jwalker\AppData\Local\Temp\pip-record-25qy8tes\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jwalker\AppData\Local\Temp\pip-install-xav63t6b\h3\

C:\Python37>cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.


C:\Python37>

```

I'm not sure why it's complaining with a **cmake required but not found** as it is clearly in my path as illustrated above. Would anyone know what the issue is?

I also tried installing via pip within a separate miniconda install and get the same error.

Any help appreciated.

**Comment by isaacbrodsky** [comment]
I'll test this when I have chance in the next few days, but my first thought to investigate is that you are calling `cmake` and `pip` via the command prompt but the install script is using Git Bash. Could you try running the same commands from Git Bash for Windows and see what the output is?

**Comment by lgrosjean** [comment]
Hi everyone, I just tried to install the package through git-bash on Windows and it worked (with cmake in my path)

**Comment by techshot25** [comment]
I don't think pip will ever be able to install h3 on windows due to the nature of make/cmake. You can instead use anaconda with `conda install h3-py -c conda-forge` which works perfectly for my home pc.

**Comment by nastasi-oq** [comment]
I'm currently working to create a wheel for h3-py.
Today I achieved  a first version that seems to work.
My plan is to build it again on a new windows machine and document all steps (and probably open a PR for some change that must be made).
Regards, Matteo.
[h3-3.4.3-cp37-cp37m-win_amd64.whl.zip](https://github.com/uber/h3-py/files/4071615/h3-3.4.3-cp37-cp37m-win_amd64.whl.zip)

**Comment by datamacgyver** [comment]
@nastasi-oq Wheel works well on my Win10 machine. Nicely done! Visual Studio and I have a very complicated relationship.
